### ISSUE TITLE
latest 1.5.0 release doesn't include binaries

### ISSUE THREAD

**Issue by calcut** [blues/note-go#51]
Is this a mistake?
1.4.9 does include binaries.

**Comment by bsatrom** [comment]
Sorry about that @calcut, I'll get this fixed.

**Comment by bsatrom** [comment]
Hey @calcut the notecard and notehub CLI binaries have been moved into the note-cli repo [here](https://github.com/blues/note-cli/releases/tag/v1.0.1)

**Comment by calcut** [comment]
fair enough! I found my way here from the docs https://dev.blues.io/tools-and-sdks/notecard-cli/
So they could do with an update at some point.

**Comment by bsatrom** [comment]
Ah, thanks for pointing that out @calcut! We'll get those links fixed.
